Import('*')

#add in the chord and check libraries
env.Append(CPPPATH=['#'])
env.Append(LIBS=['fsm']);
env.Append(LIBPATH=['#src'])

whitespace_example = env.Program('whitespace', ['whitespace.c'])
bencode_example = env.Program('bencode', ['bencode.c'])
date_example = env.Program('date', ['date.c'])
uri_rfc3986_example = env.Program('uri-rfc3986', ['uri-rfc3986.c'])
uri_rfc2396_example = env.Program('uri-rfc2396', ['uri-rfc2396.c'])

Requires(whitespace_example, libfsm)
Requires(bencode_example, libfsm)
Requires(date_example, libfsm)
Requires(uri_rfc3986_example, libfsm)
Requires(uri_rfc2396_example, libfsm)
