Import('*')

#add in the chord and check libraries
env.Append(CPPPATH=['#'])
env.Append(LIBS=['fsm']);
env.Append(LIBPATH=['#'])

whitespace_example = env.Program('whitespace', ['whitespace.c'])

Requires(whitespace_example, libfsm)
