Import('*')

#add in the chord and check libraries
env.Append(CPPPATH=['#'])
env.Append(LIBS=['fsm']);
env.Append(LIBPATH=['#src'])

whitespace_example = env.Program('whitespace', ['whitespace.c'])
bencode_example = env.Program('bencode', ['bencode.c'])
date_example = env.Program('date', ['date.c'])
uri_example = env.Program('uri', ['uri.c'])

Requires(whitespace_example, libfsm)
Requires(bencode_example, libfsm)
Requires(date_example, libfsm)
Requires(uri_example, libfsm)
